services:
  auto-xe-reg:
    container_name: auto-xe-reg
    image: gvenzl/oracle-xe
    ports: 
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=PLACEPASSWORDHERE
    volumes:
      - db-vol-reg:/opt/oracle/oradata
      - ./db_init_scripts:/container-entrypoint-initdb.d
    hostname: database
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 100
  auto-ords-reg:
    container_name: auto-ords-reg
    restart: always
    depends_on:
      auto-xe-reg:
        condition: service_healthy
    volumes:
      - ./ords_secrets:/opt/oracle/variables
      - ./ords_init_scripts:/ords-entrypoint.d/
      - ords-config-reg:/etc/ords/config
    ports:
      - 8181:8181
    image: container-registry.oracle.com/database/ords:latest
volumes:
  db-vol-reg:
    name: db-vol-reg
    external: false
  ords-config-reg:
    name: ords-config-reg
networks:
  default:
    name: ords-database-network
